version: "3.9"
services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Mapea el puerto 3000 del contenedor al 3000 del host
    volumes:
      - .:/app # Monta tu directorio local en el contenedor
      - /app/node_modules # Evita conflictos con node_modules del host
