// Configuración de ambientes
export const ENV_CONFIG = {
  API: {
    BASE_URL:
      process.env.NEXT_PUBLIC_API_BASE_URL || "http://localhost:9081/api",
    ENDPOINTS: {
      LOGIN: "/auth/login",
      LOGOUT: "/auth/logout",
      SKILLS: "/skill",
      CATEGORIAS: "/categoria",
      SUB_CATEGORIAS_BY_CATEGORIA: "/sub-categoria/categoria",
      SKILLS_BY_SUB_CATEGORIA: "/skill/sub-categoria",
      SERVICIOS: "/servicio",
      BUSQUEDA_SERVICIOS: "/servicio/busqueda",
      SERVICIO_DETALLE: "/servicio/details/preview",
      SERVICIO_REVIEWS: "/servicios/review",
      SERVICIOS_PROVEEDOR: "/servicio/proveedor",
      SOLICITUDES_CLIENTE: "/usuario/own/match",
      SOLICITUDES_PROVEEDOR: "/usuario/proveedor/match",
      MATCH: "/match",
      ACCEPT_SOLICITUD: "/match/accept/$1",
      CHAT: "/chat",
      UPLOAD: "/upload",
      CHAT_CONVERSATION_BY_ID: "/chat",
      USUARIO: "/usuario",
      USUARIO_AUTH: "/usuario/auth",
      CHECK_USER_EXISTS: "/usuario/exists",
      USUARIO_OWN_SKILLS_INFO: "/usuario/own/skills/info",
      AVERAGE_SCORE_MATCHS_PROVEEDOR: "match/average-score/proveedor/$1",
      USUARIO_OWN_SKILLS: "/usuario/own/skills",
      ADD_SKILL_TO_PROFILE: "/usuario/own/skill",
      CHECK_SKILL_IN_SERVICIOS_PROVEEDOR:
        "/usuario/own/skill/$1/exists-in-servicios",
      CHECK_AVAILABLE_MATCH_FOR_SERVICIO: "/usuario/own/match/available/$1",
      USUARIO_OWN_MATCH: "/usuario/own/match",
      DELETE_SKILL_FROM_PROFILE: "/usuario/own/skill/$1",
      CONFIRMACION_PAGO_RECEPCION: "/match/confirmacion-recepcion-pago",
      MATCH_REUNION: "/match/reunion",
      SIMPLE_CHECK: "/simple-check",
    },
  },
};
